name: GitHub Content
on:
  push:
    branches: "main"
    paths: "src/**"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJson(github) }}" > github_output.txt
      - name: Sauvegarder le fichier de sortie
        uses: actions/upload-artifact@v4.6.2
        with:
            name: github-output
            path: github_output.txt
    
