name: GitHub Content
on:
  push:
    branches: "main"
    paths: "src/**"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.event.sender.avatar_url }}"
