name: Hello Action
on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore: [ "src/**", "Dockerfile", "README.md" ]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jensone/hello-action@1.5
        with:
          name: Martin
