name: Hello Action
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.author }}" >>> entrypoint.sh
      - uses: actions/checkout@v4
      - uses: jensone/hello-action@v1.4
        with:
          name: Martin
