# Nom du workflow
name: Talk Weather

# Déclencheur de l'action
on:
    # au push sur main
    push:
        branches:
            - main
    # Clique sur le bouton 
    workflow_dispatch:
    # Chaque 2 minutes
    schedule:
        - cron: "*/2 * * * *"

# Les tâches à exécuter
jobs:
    # Nom de la tâche
    ask-weather:
        # Environnement
        runs-on: ubuntu-latest
        # Étapes
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # Action de l'API de météo
            - name: Get the weather
              run: |
                wttr=$(curl -s https://wttr.in/Paris?format=3)
                prompt="Résume la météo à Paris à partir de la réponse suivante : $wttr"
                echo $prompt > prompt.txt

            - name: OpenAI
              uses: Just-Moh-it/openai@v0.0.1
              with:
                openai-api-key: ${{ secrets.OPENAI_API_KEY }}
                openai-mode: "completion"
                openai-params: '{"prompt":"Repeat after me, Hello World: }}", "model": "text-davinci-003"}'
              id: openai