# Nom du workflow
name: Talk Weather

# Déclencheur de l'action
on:
    schedule:
        # Chaque 2 minutes
        - cron: "*/2 * * * *"

# Les tâches à exécuter
jobs:
    # Nom de la tâche
    ask-weather:
        # Environnement
        runs-on: ubuntu-latest
        # Étapes
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # Action de l'API de météo
            - name: Get the weather
              run: |
                curl wttr.in/Paris