# Nom du workflow
name: Talk Weather

# Déclencheur de l'action
on:
    # au push sur main
    push:
        branches:
            - prod
    # Clique sur le bouton 
    workflow_dispatch:
    
# Les tâches à exécuter
jobs:
    # Nom de la tâche
    ask-weather-linux:
        # Environnement
        runs-on: ubuntu-latest
        # Étapes
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: read my file
              run: cat README.md

            - name: test npm
              run: npm init -y
            
            # Action de l'API de météo
            - name: Get weather on Linux
              run: curl -s https://wttr.in/Paris?format=3
    
              # Nom de la tâche
    ask-weather-windows:
        # Environnement
        runs-on: windows-latest
        # Étapes
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            # Action de l'API de météo
            - name: Get weather on Windows
              run: Invoke-WebRequest -Uri "https://wttr.in/Paris?format=3"
